version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://radar:radar@postgres:5432/radar
      - REDIS_URL=redis://redis:6379/0
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
    networks:
      - radar-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=radar
      - POSTGRES_PASSWORD=radar
      - POSTGRES_DB=radar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - radar-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - radar-network

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - radar-network

volumes:
  postgres_data:
  redis_data:

networks:
  radar-network:
    driver: bridge

